# Generated by Django 3.1 on 2020-09-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIN_TYPE', models.CharField(max_length=200)),
                ('IM_NUMIDENT', models.IntegerField(max_length=8, unique=True)),
                ('IAN_RO_SERIA', models.CharField(max_length=200)),
                ('IAN_RO_CODE', models.IntegerField()),
                ('IAN_RO_DT', models.DateTimeField()),
                ('DIC_NAME', models.CharField(max_length=200)),
                ('F_ADR', models.CharField(max_length=300)),
                ('IA_PHONE_CODE', models.CharField(max_length=200)),
                ('IA_PHONE', models.CharField(max_length=200)),
                ('IA_EMAIL', models.CharField(max_length=200)),
                ('IND_OBL', models.CharField(max_length=200)),
                ('K_NAME', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('update_date', models.DateTimeField()),
                ('changes', models.CharField(max_length=800)),
            ],
        ),
    ]
