# Generated by Django 3.1 on 2020-09-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='IAN_FULL_NAME',
            field=models.CharField(default='sf', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='IM_NUMIDENT',
            field=models.IntegerField(unique=True),
        ),
    ]
