# Generated by Django 3.1 on 2020-09-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0002_auto_20200924_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='DIC_NAME',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='F_ADR',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IAN_RO_CODE',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IAN_RO_DT',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IAN_RO_SERIA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IA_EMAIL',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IA_PHONE',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IA_PHONE_CODE',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='IND_OBL',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='K_NAME',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='abbreviation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='changes',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='update_date',
            field=models.DateTimeField(null=True),
        ),
    ]
