# Generated by Django 3.1.1 on 2020-09-27 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0006_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 27, 13, 11, 16, 455566)),
        ),
    ]
