# Generated by Django 3.1.2 on 2020-10-07 15:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_app', '0007_auto_20200927_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email2',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 18, 45, 2, 318739)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
