# Generated by Django 3.1.2 on 2020-10-07 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0008_auto_20201007_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 7, 19, 15, 42, 814993)),
        ),
    ]
