# Generated by Django 3.1.2 on 2020-10-11 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0010_auto_20201009_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='IM_NUMIDENT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 13, 16, 21, 539154)),
        ),
    ]
