# Generated by Django 3.1.2 on 2020-10-20 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0011_auto_20201011_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='action_base',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='bank_props',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='fio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 17, 51, 39, 556620)),
        ),
    ]
