# Generated by Django 3.1.2 on 2020-10-20 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0012_auto_20201020_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyuser',
            old_name='fio',
            new_name='pib',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 19, 25, 45, 97091)),
        ),
    ]
