# Generated by Django 3.1.2 on 2020-10-20 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0013_auto_20201020_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='action_base',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='bank_props',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='pib',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='request',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 22, 48, 34, 669864)),
        ),
    ]
