# Generated by Django 3.1.2 on 2020-10-21 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0014_auto_20201020_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='IM_NUMIDENT',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='IM_NUMIDENT',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 12, 7, 49, 713880)),
        ),
    ]
