# Generated by Django 3.1.2 on 2020-10-21 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0015_auto_20201021_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='IM_NUMIDENT',
        ),
        migrations.RemoveField(
            model_name='request',
            name='IM_NUMIDENT',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 12, 26, 37, 881274)),
        ),
    ]
