# Generated by Django 3.1.2 on 2020-10-28 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0016_auto_20201021_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='action_base',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='bank_props',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='pib',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='position',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 16, 53, 40, 755591)),
        ),
    ]
