# Generated by Django 3.1.2 on 2020-10-28 14:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0017_auto_20201028_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IM_NUMIDENT', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('bank_props', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('pib', models.CharField(blank=True, max_length=200)),
                ('action_base', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 16, 54, 24, 508598)),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.companyinfo'),
        ),
        migrations.AlterField(
            model_name='request',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.companyinfo'),
        ),
    ]
