# Generated by Django 3.1.2 on 2020-10-28 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0018_auto_20201028_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='IM_NUMIDENT',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 17, 1, 0, 30165)),
        ),
    ]
