# Generated by Django 3.1.2 on 2020-10-28 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0020_auto_20201028_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='IAN_FULL_NAME',
            field=models.CharField(default='acsasc', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 17, 12, 49, 661829)),
        ),
    ]
