# Generated by Django 3.1.2 on 2020-10-28 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0021_auto_20201028_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='address',
            new_name='info_address',
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 17, 38, 25, 203072)),
        ),
    ]
