# Generated by Django 3.1.2 on 2020-11-14 11:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_app', '0022_auto_20201028_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 13, 45, 17, 181849)),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('calc_type', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('enough_data', models.BooleanField(default=False)),
                ('user_company', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=False)),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.companyinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
