# Generated by Django 3.1.2 on 2020-11-14 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0023_auto_20201114_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reporting_date',
            field=models.DateField(default='2020-11-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 15, 36, 15, 936071)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 15, 36, 15, 936071)),
        ),
    ]
