# Generated by Django 3.1.2 on 2020-11-14 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0024_auto_20201114_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 18, 51, 47, 228045)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 18, 51, 47, 228045)),
        ),
    ]
