# Generated by Django 3.1.2 on 2020-11-14 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0025_auto_20201114_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='IM_NUMIDENT',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='IM_NUMIDENT',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 20, 26, 54, 803244)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 14, 20, 26, 54, 802244)),
        ),
    ]
