# Generated by Django 3.1.2 on 2020-11-29 17:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0030_auto_20201129_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.companyusercontract'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 19, 18, 47, 418726)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 29, 19, 18, 47, 417694)),
        ),
    ]
