# Generated by Django 3.1.2 on 2020-12-12 16:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_app', '0032_auto_20201129_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_contract', models.CharField(max_length=200)),
                ('file_location', models.CharField(max_length=200)),
                ('full_payment_amount', models.FloatField()),
                ('current_payment_amount', models.FloatField()),
                ('paid_in_full', models.BooleanField(default=False)),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.companyinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='contract',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 18, 40, 37, 920210)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 18, 40, 37, 920210)),
        ),
        migrations.DeleteModel(
            name='CompanyUserContract',
        ),
    ]
