# Generated by Django 3.1.2 on 2020-12-12 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0035_auto_20201212_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='signed_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='signed_by_us',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 19, 7, 59, 884199)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 12, 19, 7, 59, 884199)),
        ),
    ]
