# Generated by Django 3.1.2 on 2020-12-13 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0037_auto_20201213_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 17, 51, 18, 703879)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 17, 51, 18, 703879)),
        ),
    ]
