# Generated by Django 3.1.2 on 2020-12-13 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0038_auto_20201213_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='file_location',
            new_name='file_location_received',
        ),
        migrations.AddField(
            model_name='documents',
            name='file_location_sended',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 20, 0, 6, 913625)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 13, 20, 0, 6, 913625)),
        ),
    ]
