# Generated by Django 3.1.2 on 2021-01-31 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0039_auto_20201213_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='IAN_RO_CODE',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 17, 58, 53, 276786)),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 31, 17, 58, 53, 276786)),
        ),
    ]
